Fail command.

diff --git a/fail/run b/fail/run
--- a/fail/run
+++ b/fail/run
@@ -1,1 +1,3 @@
-alsdjflsdjfsldfjalfjldfsj
+#!/usr/bin/env bash
+echo 'fail'
+exit 1
